name: Script
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stage 1
      run: |
        echo Processing Stage 1
        exec 3>&1 &>/dev/null
        sudo apt update
        sudo apt -y install xmltv retry
        wget http://webgrabplus.com/sites/default/files/download/SW/V3.2.0/WebGrabPlus_V3.2_install.tar.gz
        tar -zxvf WebGrabPlus_V3.2_install.tar.gz
        cd .wg++
        ./install.sh
        mv ../1.xml WebGrab++.config.xml
        mv ../2.xml WebGrab++.config2.xml
        retry ./run.sh || mv WebGrab++.config.xml WebGrab++.config_og.xml && mv WebGrab++.config2.xml WebGrab++.config.xml && ./run.sh
        mv /home/runner/work/MattTheTekie/MattTheTekie/.wg++/guide.xml /home/runner/work/MattTheTekie/MattTheTekie/.wg++/1.xml
    - name: Stage 2
      uses: actions/upload-artifact@master
      with:
        name: 1.xml
        path: /home/runner/work/MattTheTekie/MattTheTekie/.wg++/1.xml
    - name: Stage 3
      run: |
        echo Processing Stage 3
        exec 3>&1 &>/dev/null
        cd /home/runner/work/MattTheTekie/MattTheTekie/.wg++/
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b main
        git add .
        git commit -m "The dragon is hunting."
        git remote add origin "https://${{ github.actor }}:${{ secrets.JAPAN }}@github.com/${{ github.repository }}"
        git push -f -u origin main
    - name: Stage 4
      run: |
        echo Processing Stage 4
        exec 3>&1 &>/dev/null
        go install github.com/aquilax/m3u-combine@latest
        cd 0        
        openvpn vpn.ovpn --auth-user-pass <(echo -e ${{ secrets.VPN_USERNAME }}"\n"${{ secrets.VPN_PASSWORD }}) &
        wget -O 0_1.m3u https://github.com/iptv-org/iptv/raw/master/streams/us_samsung.m3u
        wget -O 0_2.m3u https://i.mjh.nz/PlutoTV/us.m3u8
        wget -O 0_3.m3u ${{ secrets.TV2 }}
        wget -O plex.m3u https://i.mjh.nz/Plex/us.m3u8
        wget -O uk_samsung.m3u https://github.com/iptv-org/iptv/raw/master/streams/uk_samsung.m3u 
        wget -O uk_rakuten.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/uk_rakuten.m3u 
        wget -O uk_sportstribal.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/uk_sportstribal.m3u 
        wget -O us_adultswim.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_adultswim.m3u 
        wget -O us_bumblebee.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_bumblebee.m3u 
        wget -O us_distro.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_distro.m3u 
        wget -O us_fubo.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_fubo.m3u 
        wget -O us_glewedtv.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_glewedtv.m3u 
        wget -O us_imdbtv.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_imdbtv.m3u 
        wget -O us_klowdtv.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_klowdtv.m3u 
        wget -O us_redbox.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_redbox.m3u 
        wget -O us_roku.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_roku.m3u 
        wget -O us_stirr.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_stirr.m3u 
        wget -O us_tcl.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_tcl.m3u 
        wget -O us_tubi.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_tubi.m3u 
        wget -O us_vizio.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_vizio.m3u 
        wget -O us_xumo.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/us_xumo.m3u 
        wget -O ie_samsung.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ie_samsung.m3u 
        wget -O ca_stingray.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ca_stingray.m3u 
        wget -O ca_samsung.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/ca_samsung.m3u 
        wget -O au_samsung.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/au_samsung.m3u 
        wget -O jp.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/jp.m3u 
        wget -O jp_org.m3u https://raw.githubusercontent.com/iptv-org/iptv/master/streams/jp.m3u 
        curl -H "Authorization: token ${{ secrets.JAPAN }}" \
        -H 'Accept: application/vnd.github.v3.raw' \
        -o 1.m3u \
        -L ${{ secrets.JP3 }}
        wget -O plex.xml https://i.mjh.nz/Plex/us.xml
        wget -O samsung.xml https://i.mjh.nz/SamsungTVPlus/all.xml
        wget -O pluto.xml https://i.mjh.nz/PlutoTV/us.xml
        curl -H "Authorization: token ${{ secrets.JAPAN }}" \
        -H 'Accept: application/vnd.github.v3.raw' \
        -o 1.xml \
        -L ${{ secrets.ONE_EPG }}
        wget -O anime.xml.gz https://epgshare01.online/epgshare01/epg_ripper_ID1.xml.gz
        gunzip anime.xml.gz
        wget -O iptvjapan.xml https://www.bevy.be/bevyfiles/japan.xml
    - name: Final Stage
      run: |
        echo Processing Final Stage
        exec 3>&1 &>/dev/null
        cd 0
        cat zoro.txt | ~/go/bin/m3u-combine > zoro.m3u
        sed 's/.png", /.png" group-title="Free TV", /' -i zoro.m3u
        cat luffy.txt | ~/go/bin/m3u-combine > 0.m3u
        sed 's/\( group-title="\)[^"]*/\1Free TV/' -i 0.m3u
        sed 's/status="online", /status="online", group-title="Free TV" '/ -i 0.m3u
        sed 's/status="blocked", /status="blocked", group-title="Free TV" '/ -i 0.m3u
        sed 's/status="timeout", /status="timeout", group-title="Free TV" '/ -i 0.m3u
        sed 's/status="error", /status="error", group-title="Free TV" '/ -i 0.m3u
        cat sanji.txt | ~/go/bin/m3u-combine > combined.m3u
        sed 's/group-title="Free TV", group-title="Free TV"/group-title="Free TV",'/ -i combined.m3u
        awk '/En Español|en español|En español|en Español|español|Español|Espanol|espanol|Latino|latino|spain|Spain|Spanish|spanish|Latin|Latin|Latido|latido| con| la| Sony Canal| Perfecto| perfecto| Mundo| amigos| escándalos| Estrella | nosotras| noticias| Cine| ViX| Tu Cine| Telemundo| Séptimo| Saber Mas| RCN Mas| RCN Más| PrendeTV| Niños| MMC| misterios sin resolver| Mi obsesión favorita| MegaNoticias| La corriente| Juntos| Investiga| Foodies| Éxitos|Crímenes imperfectos| Corazón|CNN RESUMEN|Chiquilines|Canela|Badass novelas| Amantes / {while (/En Español|en español|En español|en Español|español|Español|Espanol|espanol|Latino|latino|spain|Spain|Spanish|spanish|Latin|Latin|Latido|latido| con| la| Sony Canal| Perfecto| perfecto| Mundo| amigos| escándalos| Estrella | nosotras| noticias| Cine| ViX| Tu Cine| Telemundo| Séptimo| Saber Mas| RCN Mas| RCN Más| PrendeTV| Niños| MMC| misterios sin resolver| Mi obsesión favorita| MegaNoticias| La corriente| Juntos| Investiga| Foodies| Éxitos|Crímenes imperfectos| Corazón|CNN RESUMEN|Chiquilines|Canela|Badass novelas| Amantes / && getline>0) ; next} 1' combined.m3u > FREE.m3u        
        mv FREE.m3u combined.m3u
        sed 's/(1080p)//' -i combined.m3u
        sed 's/(720p)//' -i combined.m3u
        sed 's/(540p)//' -i combined.m3u
        sed -i 's/\[//' -i combined.m3u
        sed -i 's/\]//' -i combined.m3u
        sed -i 's/(YouTube)//' -i combined.m3u
        sed -s 's/(French AI Translated Closed-Captioning)//' -i combined.m3u
        sed -s 's/(Bahasa Indonesia AI Translated Closed-Captioning)//' -i combined.m3u
        sed -s 's/(Chinese Traditional AI Translated Closed-Captioning)//' -i combined.m3u
        sed -s 's/Not 24\/7//' -i combined.m3u
        sed -s 's/(480p)//' -i combined.m3u
        sed -s 's/(360p)//' -i combined.m3u
        sed -s 's/(240p)//' -i combined.m3u
        sed -s 's/(England)//' -i combined.m3u
        sed -s 's/(144p)//' -i combined.m3u
        sed -s 's/(474p)//' -i combined.m3u
        sed -s 's/(2160p)//' -i combined.m3u
        sed -s 's/(STIRR)//' -i combined.m3u
        sed -s 's/(Canada)//' -i combined.m3u
        sed -s 's/(Test for Bitcentral)//' -i combined.m3u
        sed -s 's/(BumbleBee TV)//' -i combined.m3u
        sed -s 's/(Bumblebee TV)//' -i combined.m3u
        sed -s 's/BumbleBee TV//' -i combined.m3u
        sed -s 's/Bumblebee TV//' -i combined.m3u
        sed -s 's/(English Subs)//' -i combined.m3u
        sed -s 's/(Indonesian Subs)//' -i combined.m3u
        sed -s 's/(XUMO)//' -i combined.m3u
        sed -s 's/(Redbox)//' -i combined.m3u
        sed -s 's/Geo-blocked//' -i combined.m3u
        sed -s 's/(768p)//' -i combined.m3u
        sed -s 's/(432p)//' -i combined.m3u
        sed -s 's/(504p)//' -i combined.m3u
        sed -s 's/(UK)//' -i combined.m3u
        sed -s 's/(576p)//' -i combined.m3u
        sed -s 's/(234p)//' -i combined.m3u
        sed -s 's/(Australia)//' -i combined.m3u
        sed -i 's/STIRR//' -i combined.m3u
        sed -i 's/US SPORT//' -i combined.m3u
        sed -i 's/STIRR CITY//' -i combined.m3u
        sed 's/group-title="Free TV",/group-title="Free TV", /' -i 'combined.m3u'
        sed 's/group-title="Free TV",  /group-title="Free TV", /' -i 'combined.m3u'
        sed 's/24\/7 Anime/247 Anime/' -i combined.m3u
        sed 's/group-title="24\/7 Anime", /group-title="24\/7 Anime", [ANIME] /' -i 'combined.m3u'
        sed 's/group-title="Japanese TV", /group-title="Japanese TV", [JAPAN] /' -i 'combined.m3u'
        sed 's/group-title="Free TV", /group-title="Free TV", [FREE] /' -i 'combined.m3u'
        sed 's/247 Anime", /247 Anime", [ANIME] /' -i 'combined.m3u'
        sed 's/247 Anime/24\/7 Anime/' -i combined.m3u
        sed 's/2014.svg.png", /2014.svg.png", [JAPAN] /' -i combined.m3u
        sed 's/247 Anime/24\/7 Anime/' -i combined.m3u
        sed 's/status="error",/status="online",/' -i combined.m3u 
        sed 's/status="timeout",/status="online",/' -i combined.m3u 
        sed 's/status="online",/status="online", group-title="Japanese TV" [JAPAN] /' -i combined.m3u 
        sed 's/group-title="Japanese TV",group-title="Japanese TV"/group-title="Japanese TV",/' -i combined.m3u
        sed 's/group-title="Japanese TV", group-title="Japanese TV" /group-title="Japanese TV", /' -i 'combined.m3u'
        sed 's/24\/7 Anime/247 Anime/' -i combined.m3u
        sed -s 's/(720p)//' -i 'combined.m3u'
        sed -s 's/(360p)//' -i 'combined.m3u'
        sed -s 's/(French AI Translated Closed-Captioning)//' -i 'combined.m3u'
        sed -s 's/(Bahasa Indonesia AI Translated Closed-Captioning)//' -i 'combined.m3u'
        sed -s 's/(Chinese Traditional AI Translated Closed-Captioning)//' -i 'combined.m3u'
        sed -s 's/(540p)//' -i 'combined.m3u'
        sed -s 's/(480p)//' -i 'combined.m3u'
        sed -s 's/(1080p)//' -i 'combined.m3u'
        sed -s 's/(720p NewHome)//' -i 'combined.m3u'
        sed -s 's/(720p Official)//' -i 'combined.m3u'
        sed -s 's/(1080p Official)//' -i 'combined.m3u'
        sed -s 's/(720p Official 2)//' -i 'combined.m3u'
        sed -s 's/(720p Stream)//' -i 'combined.m3u'
        sed -s 's/(720p iHome)//' -i 'combined.m3u'
        sed -s 's/(English Subs)//' -i 'combined.m3u'
        sed -s 's/[][]//' -i 'combined.m3u'
        sed -s 's/Not 24\/7//' -i 'combined.m3u'
        sed -s 's/JAPAN]//' -i 'combined.m3u'
        sed -s 's/[[]]//' -i 'combined.m3u'
        sed -i 's/(YouTube)//' -i 'combined.m3u'
        sed 's/group-title="Japanese TV",/group-title="Japanese TV",[JAPAN]/' -i 'combined.m3u'
        sed -i 's/  / /' -i 'combined.m3u'
        sed 's/2014.svg.png", /2014.svg.png", [JAPAN] /' -i combined.m3u 
        sed 's/247 Anime/24\/7 Anime/' -i 'combined.m3u'
        sed -i '/H3D90/d' combined.m3u
        sed 's/ABC News/ABC N2/' -i 'combined.m3u'
        sed -i '/ABC N2/d' combined.m3u
        sed -i '/AccuWeather Now/d' combined.m3u
        sed -i '/BACKSTAGE/d' combined.m3u
        sed -i '/Bein Sport Xtra/d' combined.m3u
        sed -i '/Bloomberg TV US/d' combined.m3u
        sed -i '/bon appétit/d' combined.m3u
        sed -i '/Buzzr/d' combined.m3u
        sed -i '/CBSN/d' combined.m3u
        sed -i '/ChiveTV/d' combined.m3u
        sed -i '/Chive TV/d' combined.m3u
        sed -i '/Dallas Cowboy Cheerleaders/d' combined.m3u
        sed -i '/Cinevault 80s/d' combined.m3u
        sed -i '/Cinevault Westerns/d' combined.m3u
        sed -i '/Degrassi The Next Generation/d' combined.m3u
        sed -i '/Dove/d' combined.m3u
        sed -i '/DryBar Comedy/d' combined.m3u
        sed -i '/Dust/d' combined.m3u
        sed -i '/EDGESport/d' combined.m3u
        sed -i '/EDGEsport/d' combined.m3u
        sed -i '/Electric Now/d' combined.m3u
        sed -i '/Euronews Portuguese/d' combined.m3u
        sed -i '/Euronews Deutsch/d' combined.m3u
        sed -i '/Euronews English/d' combined.m3u
        sed -i '/Vevo 80s/d' combined.m3u
        sed -i '/Zoo Moo/d' combined.m3u
        sed -i '/QVC Live/d' combined.m3u
        sed -i '/Qello Concerts by Stingray/d' combined.m3u
        sed -i '/Outside TV/d' combined.m3u
        sed -i '/NBC News Now/d' combined.m3u
        sed -i '/Mystery Science Theater 3000/d' combined.m3u
        sed -i '/MavTV Select/d' combined.m3u
        sed -i '/MOVIESPHERE/d' combined.m3u
        sed -i '/MavTV/d' combined.m3u
        sed -i '/LEGO Channels/d' combined.m3u
        sed -i '/Kidoodle TV/d' combined.m3u
        sed -i '/Ion Plus/d' combined.m3u
        sed -i '/GUSTOTV/d' combined.m3u
        sed -i '/Glory Kickboxing/d' combined.m3u
        sed -i '/Fuel TV/d' combined.m3u
        sed -i '/FTF Sports/d' combined.m3u
        sed -i '/FTF For the fans/d' combined.m3u
        sed -i '/FilmStreams/d' combined.m3u
        sed -i '/Chicken Soup For The Soul/d' combined.m3u
        sed -i '/Euronews Italiano/d' combined.m3u
        sed -i '/FilmRise Classic TV on Redbox/d' combined.m3u
        sed -i '/Fox Soul/d' combined.m3u
        sed -i '/fubo Sports Network/d' combined.m3u
        sed -i '/Newsmax/d' combined.m3u
        sed -i '/ PersuitUp/d' combined.m3u
        sed -i '/PeopleTV/d' combined.m3u
        sed -i '/Pac 12 Insider/d' combined.m3u
        sed -i '/Pac12 Insider/d' combined.m3u
        sed -i '/People are Awesome/d' combined.m3u
        sed -i '/Qwest TV Classical/d' combined.m3u
        sed -i '/Qwest TV Mix/d' combined.m3u
        sed -i '/Qwest TV Jazz & Beyond/d' combined.m3u
        sed -i '/Real nosey/d' combined.m3u
        sed -i '/Reelz/d' combined.m3u
        sed -i '/RetroCrush TV/d' combined.m3u
        sed -i '/Revry News/d' combined.m3u
        sed -i '/Shout! Factory/d' combined.m3u
        sed -i '/Shout! Factory TV Stream/d' combined.m3u
        sed -i '/Slightly Off by IFC/d' combined.m3u
        sed -i '/So Yummy!/d' combined.m3u
        sed -i '/Stingray Djazz/d' combined.m3u
        sed -i '/Surf Now TV/d' combined.m3u
        sed -i '/The Jack Hannah Channel/d' combined.m3u
        sed -i '/Today All Day/d' combined.m3u
        sed -i '/USA TODAY/d' combined.m3u
        sed -i '/USA TODAY Sportswire/d' combined.m3u
        sed -i '/Weatherspy/d' combined.m3u
        sed -i '/Weathernation/d' combined.m3u
        sed -i '/The Young Turks/d' combined.m3u
        sed -i '/IGN1/d' combined.m3u
        sed -i '/IGN TV/d' combined.m3u
        sed -i '/s Voice News/d' combined.m3u
        sed -i '/ PersuitUp/d' combined.m3u
        sed -i '/Moonbug Kids/d' combined.m3u
        sed -i '/AsianCrush/d' combined.m3u
        sed -i '/Yahoo! Finance/d' combined.m3u
        sed 's/MagellanTV NOW/Magellan TV Now 2/' -i combined.m3u
        sed -i '/beIN Sports Xtra/d' combined.m3u
        sed -i '/Tastemade France/d' combined.m3u
        sed 's/All Reality by WE tv/All Reality WE tv 2/' -i combined.m3u
        sed 's/Anime All day/Anime All Day 2/' -i combined.m3u
        sed 's/ BABY SHARK TV/ Baby Shark TV 2/' -i combined.m3u
        sed -i '/EstrellaTV/d' combined.m3u
        sed -i '/Freebie TV - Los Pitufos/d' combined.m3u
        sed -i '/Grande-ish/d' combined.m3u
        sed -i '/Lucha Libre AAA/d' combined.m3u
        sed -i '/Misterios sin resolver/d' combined.m3u
        sed -i '/ MOTORVISION.TV/d' combined.m3u
        sed -i '/ Nosey Escándalos/d' combined.m3u
        sed -i '/ Nosey Casos/d' combined.m3u
        sed -i '/ So...Real/d' combined.m3u
        sed -i '/Pelis y Popcorn/d' combined.m3u
        sed -i '/ El Conflicto TV/d' combined.m3u
        sed -i '/ Emergencia 911/d' combined.m3u
        sed -i '/ Spike ¡extremo!/d' combined.m3u
        sed -i '/ Fight Network/d' combined.m3u
        sed -i '/ Horrorfy/d' combined.m3u
        sed -i 's/24\/7 TV", /24\/7 TV", [24\/7] /' -i combined.m3u
        sed -i 's/group-title="24\/7 TV", [24\/7]/group-title="24\/7 TV"/' -i combined.m3u
        sed 's/] 24\/7  /] /' -i 'combined.m3u' 
        sed 's/ 24\/7 //' -i 'combined.m3u' 
        sed 's/7]/7] /' -i 'combined.m3u' 
        sed 's/7]  /7] /' -i 'combined.m3u' 
        sed 's/247 TV/24\/7 TV/' -i 'combined.m3u'
        sed 's/group-title="24\/7 TV",TV/group-title="24\/7 TV",24\/TV/' -i 'combined.m3u'
        sed 's/group-title="24\/7 TV",24\/TV/group-title="24\/7 TV", [24\/7 TV]/' -i 'combined.m3u'
        sed 's/group-title="Free TV", FREE]/group-title="Free TV", [FREE]/' -i 'combined.m3u'
        sed 's/group-title="24\/7 Anime", ANIME]/group-title="24\/7 Anime", [ANIME]/' -i 'combined.m3u'
        sed 's/group-title="Documentary", DOC]/group-title="Documentary", [DOC]/' -i 'combined.m3u'
        mv combined.m3u combined1.m3u
        cat hehehee.txt | ~/go/bin/m3u-combine > combined.m3u
        python3 ace.py
        python3 new_world_order.py
        sed -i 's/group-title="Japanese TV", \[JAPAN\] JAPAN/group-title="Japanese TV", \[JAPAN\]/' combined.m3u
        sed -i 's/group-title="24\/7 Anime", \[ANIME\] ANIME/group-title="24\/7 Anime", \[ANIME\]/' combined.m3u
        sed -i 's/group-title="24\/7 Cartoon",/group-title="24\/7 Cartoon", \[TOON\]/' combined.m3u
        sed -i 's/group-title="Free TV", \[FREE\] /group-title="Free TV", /' combined.m3u
        sed -i 's/group-title="Free TV", /group-title="Free TV", \[FREE\] /' combined.m3u
        mv combined.m3u combined_draft.m3u
        sed 's/",/" group-title="Japanese TV", \[JAPAN\] /' -i 'jp_org.m3u'
        cat linux.txt | ~/go/bin/m3u-combine > combined.m3u
        touch merge.xml
        tv_merge -i 1.xml -m iptvjapan.xml -o japan1.xml
        tv_merge -i japan1.xml -m pluto.xml -o free1.xml
        tv_merge -i pluto.xml -m anime.xml -o free2.xml
        tv_merge -i free2.xml -m plex.xml -o free3.xml
        tv_merge -i free3.xml -m samsung.xml -o free4.xml
        tv_merge -i free4.xml -m free1.xml -o merge.xml
        rm -rf ../.git/objects/pack
        mkdir 1 && cd 1
        wget ${{ secrets.YAY }}
        unzip site.zip
        cp /home/runner/work/MattTheTekie/MattTheTekie/0/combined.m3u /home/runner/work/MattTheTekie/MattTheTekie/0/1/SATANSLAYER666_666_hehehe_combined.m3u
        cp /home/runner/work/MattTheTekie/MattTheTekie/0/merge.xml /home/runner/work/MattTheTekie/MattTheTekie/0/1/SATANSLAYER666_666_hehehe_merge.xml
    - name: Push
      uses: dswistowski/surge-sh-action@v1
      with:
         domain: ${{ secrets.surge_domain }}
         project: '/home/runner/work/MattTheTekie/MattTheTekie/0/1'
         login: ${{ secrets.surge_login }}
         token: ${{ secrets.surge_token }}
